# Generated by Django 5.2.4 on 2025-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_spotimages_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
