# Generated by Django 5.2.4 on 2025-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_spots_top_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
