# Generated by Django 5.2.4 on 2025-07-13 10:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_spots_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=250, null=True, populate_from='title', unique=True),
        ),
    ]
