# Generated by Django 5.2.4 on 2025-07-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_spots_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
