# Generated by Django 5.2.4 on 2025-07-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_spots_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
