# Generated by Django 5.2.4 on 2025-07-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
